//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ncsln.DBModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class vInternalStock
    {
        public int Id { get; set; }
        public string CompanyName { get; set; }
        public string Title { get; set; }
        public string Code { get; set; }
        public Nullable<System.DateTime> StockDate { get; set; }
        public Nullable<int> Qty { get; set; }
        public Nullable<bool> Type { get; set; }
        public string Stock { get; set; }
        public int ItemId { get; set; }
    }
}
